# -*- mode: python ; coding: utf-8 -*-
"""
PyInstaller spec for CraftBotInstaller.exe — the small wizard/installer.

Bundles ONLY: craftbot.py, the installer/ package (api/helpers/metadata/
payload/wizard + the web/ assets), pywebview's runtime bindings, the icon
files, and a VERSION file. No agent code, no openai/anthropic/chromadb —
those live in the agent zip that this installer downloads from GitHub
Releases at install time.

Wizard UI runs in the OS-native webview (WebView2 on Windows, WKWebView
on macOS, WebKitGTK on Linux) styled via installer/web/{html,css,js}.
We bundle pywebview itself but rely on the OS-provided webview engine —
no Chromium ships inside the EXE.

Result: ~15–25 MB onefile EXE. Double-click → wizard. CLI subcommands
(install / start / stop / status / uninstall / repair) still work.

Build from the repo root: `python -m PyInstaller packaging/CraftBotInstaller.spec`.
All paths below are derived from SPECPATH (the absolute directory of this
spec file), so the build works regardless of the current working directory.
"""

import os as _os

from PyInstaller.utils.hooks import collect_all as _collect_all

# SPECPATH is set by PyInstaller to the directory containing this spec file
# (i.e. <repo>/packaging/). ROOT walks one level up to the project root so
# we can reference craftbot.py, installer/, assets/, rthooks/ etc. via
# absolute paths.
ROOT = _os.path.dirname(SPECPATH)

# Pull in pywebview's bundled JS bridge files + platform backend (edgechromium
# on Windows, cocoa on macOS, gtk on Linux). collect_all returns a tuple
# (datas, binaries, hiddenimports) — splatted into the Analysis() call below.
_webview_datas, _webview_binaries, _webview_hiddenimports = _collect_all('webview')

datas = [
    # The installer/ package — wizard + helpers + metadata + payload modules.
    # Top-level imports in craftbot.py mean PyInstaller's analyser already
    # bundles these as bytecode, but we keep the source files alongside so
    # tracebacks and debugging show real lines instead of <frozen ...>.
    (_os.path.join(ROOT, 'installer'), 'installer'),
    (_os.path.join(ROOT, 'craftbot_logo_1.ico'), '.'),
    (_os.path.join(ROOT, 'craftbot_logo_1.png'), '.'),
    # Brand assets used by the wizard header. We only ship the few PNGs we
    # actually display — not the whole assets/ folder, which is megabytes
    # of marketing screenshots that bloat the installer.
    (_os.path.join(ROOT, 'assets', 'craftbot_logo_text_no_border_dark.png'), 'assets'),
    # pywebview's own bundled assets (the JS bridge file it injects into
    # every webview, plus its config). collect_all already gathers them but
    # they go in datas, not binaries.
    *_webview_datas,
]

# VERSION file is generated by the release workflow (echo of the git tag)
# at the project root. Bundle it if present so
# craftbot._read_bundled_version() pins the installer to the matching agent
# version.
_version_path = _os.path.join(ROOT, 'VERSION')
if _os.path.isfile(_version_path):
    datas.append((_version_path, '.'))


a = Analysis(
    [_os.path.join(ROOT, 'craftbot.py')],
    pathex=[ROOT],  # so `import craftbot` and `from installer import ...` resolve
    binaries=list(_webview_binaries),
    datas=datas,
    hiddenimports=list(_webview_hiddenimports),
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[
        # Same hooks the agent uses. The installer is also console=False so
        # any subprocess it spawns (powershell for shortcut, schtasks for
        # auto-start, taskkill for stop) would otherwise flash a console.
        _os.path.join(ROOT, 'rthooks', 'rthook-utf8-stdio.py'),
        _os.path.join(ROOT, 'rthooks', 'rthook-windows-noflash.py'),
    ],
    excludes=[
        # Be aggressive — none of this belongs in the installer EXE.
        'torch', 'torchvision', 'torchaudio', 'triton', 'nvidia',
        'transformers', 'cv2', 'matplotlib', 'tensorflow',
        'openai', 'anthropic', 'chromadb', 'tiktoken', 'tiktoken_ext',
        'fastapi', 'starlette', 'uvicorn', 'pydantic',
        'numpy', 'scipy', 'pandas', 'sklearn',
        # The agent's own modules — installer never imports them
        'app', 'agent_core', 'agents', 'decorators', 'skills',
    ],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='CraftBotInstaller',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,  # No terminal flash on double-click; wizard owns the UX
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=_os.path.join(ROOT, 'craftbot_logo_1.ico'),
)
